apiVersion: apps/v1
kind: Deployment
metadata:
  name: anyscale-operator
  namespace: {{ .Release.Namespace }}
  labels:
    app: anyscale-operator
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.operatorReplicas }}
  selector:
    matchLabels:
      app: anyscale-operator
  template:
    metadata:
      labels:
        app: anyscale-operator
        {{- if eq .Values.cloudProvider "azure" }}
        azure.workload.identity/use: "true"
        {{- end }}
      {{- if eq .Values.cloudProvider "azure" }}
      annotations:
        azure.workload.identity/inject-proxy-sidecar: "true"
      {{- end }}
    spec:
      serviceAccount: anyscale-operator
      {{- if .Values.operatorNodeSelection.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.operatorNodeSelection.nodeSelector | indent 8 }}
      {{- else if .Values.operatorNodeSelection.affinity }}
      affinity:
{{ toYaml .Values.operatorNodeSelection.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.operatorNodeSelection.tolerations }}
      tolerations:
{{ toYaml .Values.operatorNodeSelection.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: operator
        image: "{{ required "operatorImage is required" .Values.operatorImage }}"
        imagePullPolicy: {{ .Values.operatorImagePullPolicy | default "IfNotPresent" }}
        command: ["/app/go/infra/kubernetes_manager/kubernetes_manager"]
        args:
        - --log-level=info
        - --log-file=/tmp/anyscale/logs/operator.log
        - start
        - --cloud-deployment-id={{ required "cloudDeploymentId is required" .Values.cloudDeploymentId }}
        - --control-plane-url={{ .Values.controlPlaneURL | default "https://console.anyscale.com" }}
        - --cloud-provider={{ .Values.cloudProvider }}
        {{- if not (or .Values.anyscaleCliToken (include "anyscale.externalSecretEnabled" .)) }}
        - --region={{ required "region is required for operator registration if anyscaleCliToken is not provided & cloud-native bootstrap scheme is used; must be set to the cloud provider region of this Kubernetes cluster" .Values.region }}
        {{ end }}
        - --patch-config-path=/tmp/config/patches.yaml
        {{- if .Values.enableGateway }}
        - --enable-gateway=true
        - --gateway-name={{ .Values.gatewayName }}
        - --gateway-hostname={{ .Values.gatewayHostname }}
        - --gateway-ip={{ .Values.gatewayIp }}
        {{- end }}
        - --system-logs-ingress-proxy-port=3100
        - --system-metrics-ingress-proxy-port=3101
        - --vector-enrichment-table-path=/tmp/config/vector/runtime_metadata.csv
        {{- if gt (int .Values.operatorReplicas) 1 }}
        - --enable-leader-election=true
        - --leader-election-lease-namespace={{ .Release.Namespace }}
        - --leader-election-lease-name=anyscale-operator-lease
        {{- end }}
        {{- if .Values.operatorExcludeComponentVerification }}
        {{- range .Values.operatorExcludeComponentVerification }}
        - --exclude-component-verification={{ . }}
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.operatorResources.operator | indent 10 }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
{{if or .Values.anyscaleCliToken (include "anyscale.externalSecretEnabled" .)}}
        - name: ANYSCALE_CLI_TOKEN
          valueFrom:
            secretKeyRef:
              name: anyscale-cli-token
              key: ANYSCALE_CLI_TOKEN
{{end}}
{{- $awsCredentialsSecret := "" }}
{{- range .Values.externalSecrets }}
{{- if eq .name "aws-credentials" }}
{{- if .enabled }}
{{- $awsCredentialsSecret = .name }}
{{- end }}
{{- end }}
{{- end }}
{{- if $awsCredentialsSecret }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ $awsCredentialsSecret }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ $awsCredentialsSecret }}
              key: AWS_SECRET_ACCESS_KEY
{{- end }}
        volumeMounts:
          - name: logs
            mountPath: /tmp/anyscale/logs/
          - name: patches
            mountPath: /tmp/config
          - name: vector-config
            mountPath: /tmp/config/vector/
      - name: vector
        image: timberio/vector:0.40.0-debian
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
        - /etc/vector/entrypoint.sh
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        resources:
{{ toYaml .Values.operatorResources.vector | indent 10 }}
        volumeMounts:
        - mountPath: /tmp/anyscale/logs/
          name: logs
        - mountPath: /etc/vector/
          name: vector
          readOnly: true
        - mountPath: /tmp/vector
          name: vector-state
        - mountPath: /tmp/config/vector/
          name: vector-config
      volumes:
        - name: logs
          emptyDir: {}
        - name: patches
          configMap:
            name: patches
        - name: vector
          projected:
            defaultMode: 420
            sources:
            - configMap:
                name: vector
        - name: vector-state
          emptyDir: {}
        - name: vector-config
          emptyDir: {}
