{{- if .Values.supportTeam.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.supportTeam.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: support-team
{{- end }}